name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v6

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - run: pip install -r requirements.txt

      - run: python -m py_compile app.py

      - run: docker build -t demo .