name: Trivy

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  scan:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v6

      - run: docker build -t demo .

      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: demo
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL